package discovery

import (
	"fmt"
	"os"
	"strings"
)

// ConfigWriter handles writing discovered configuration to a YAML file
type ConfigWriter struct {
	Path   string
	Config *GeneratedConfig
}

// GeneratedConfig represents the generated config structure
type GeneratedConfig struct {
	Version   int           `yaml:"version"`
	Logging   LoggingConfig `yaml:"logging"`
	Routing   RoutingConfig `yaml:"routing"`
	Providers []EnvProvider `yaml:"providers,omitempty"`
	Local     LocalConfig   `yaml:"local,omitempty"`
}

// LoggingConfig controls log verbosity
type LoggingConfig struct {
	Level string `yaml:"level"`
}

// RoutingConfig holds global routing parameters
type RoutingConfig struct {
	DefaultModel       string `yaml:"default_model"`
	LatencyThresholdMs int    `yaml:"latency_threshold_ms"`
	FallbackEnabled    bool   `yaml:"fallback_enabled"`
}

// LocalConfig contains local node definitions
type LocalConfig struct {
	Nodes []EnvProvider `yaml:"nodes,omitempty"`
}

// NewConfigWriter creates a new ConfigWriter
func NewConfigWriter(path string) *ConfigWriter {
	return &ConfigWriter{
		Path: path,
		Config: &GeneratedConfig{
			Version: 2,
			Logging: LoggingConfig{Level: "INFO"},
			Routing: RoutingConfig{
				DefaultModel:       "",
				LatencyThresholdMs: 2000,
				FallbackEnabled:    true,
			},
			Providers: make([]EnvProvider, 0),
		},
	}
}

// SetDefaultModel sets the default model for routing
func (w *ConfigWriter) SetDefaultModel(model string) {
	w.Config.Routing.DefaultModel = model
}

// AddEnvProvider adds an environment-based provider to the config
func (w *ConfigWriter) AddEnvProvider(ep EnvProvider) {
	w.Config.Providers = append(w.Config.Providers, ep)
}

// AddNetworkInstance adds a discovered network instance as a local node
func (w *ConfigWriter) AddNetworkInstance(instance LocalRouterInstance) {
	provider := EnvProvider{
		ID:             fmt.Sprintf("localrouter-%s", strings.ReplaceAll(instance.IP, ".", "-")),
		Type:           "openai-compatible",
		Endpoint:       fmt.Sprintf("http://%s:%s/v1", instance.IP, instance.Port),
		Priority:       500 + len(w.Config.Providers), // Lower priority than env-based
		IsFree:         true,
		Models:         instance.Models,
		RecoveryWindow: "5m",
		TimeoutMs:      30000,
	}
	w.Config.Providers = append(w.Config.Providers, provider)
}

// Write generates and writes the configuration to a YAML file
func (w *ConfigWriter) Write() error {
	var lines []string

	// Header
	lines = append(lines, "# Generated by LocalRouter Discovery")
	lines = append(lines, fmt.Sprintf("# Providers discovered: %d", len(w.Config.Providers)))
	lines = append(lines, "")

	// Version
	lines = append(lines, "version: 2")

	// Logging
	lines = append(lines, "")
	lines = append(lines, "logging:")
	lines = append(lines, fmt.Sprintf("  level: %s", w.Config.Logging.Level))

	// Routing
	lines = append(lines, "")
	lines = append(lines, "routing:")
	if w.Config.Routing.DefaultModel != "" {
		lines = append(lines, fmt.Sprintf("  default_model: %s", w.Config.Routing.DefaultModel))
	}
	lines = append(lines, fmt.Sprintf("  latency_threshold_ms: %d", w.Config.Routing.LatencyThresholdMs))

	// Providers
	if len(w.Config.Providers) > 0 {
		lines = append(lines, "")
		lines = append(lines, "providers:")

		for _, p := range w.Config.Providers {
			lines = append(lines, "")
			lines = append(lines, fmt.Sprintf("  - id: %s", p.ID))
			lines = append(lines, fmt.Sprintf("    type: %s", p.Type))
			if p.Endpoint != "" {
				lines = append(lines, fmt.Sprintf("    endpoint: %s", p.Endpoint))
			}
			lines = append(lines, fmt.Sprintf("    api_key: ${%s}", p.EnvVar))
			lines = append(lines, fmt.Sprintf("    recovery_window: %s", p.RecoveryWindow))
			if p.ChatPath != "" {
				lines = append(lines, fmt.Sprintf("    chat_path: %s", p.ChatPath))
			}
			if p.TimeoutMs > 0 && p.Type == "ollama" {
				lines = append(lines, fmt.Sprintf("    timeout_ms: %d", p.TimeoutMs))
			}

			// Add rate limits for free providers
			if p.IsFree {
				lines = append(lines, "    limits:")
				lines = append(lines, "      requests: 100")
				lines = append(lines, "      window: 1m")
			}

			lines = append(lines, "    models:")
			for _, model := range p.Models {
				lines = append(lines, fmt.Sprintf("      - id: %s", model))
				if p.IsFree {
					lines = append(lines, "        is_free: true")
				}
			}
		}
	}

	// Write to file
	content := strings.Join(lines, "\n")
	return os.WriteFile(w.Path, []byte(content), 0644)
}

// GenerateConfigFromEnv generates a config from discovered environment providers
func GenerateConfigFromEnv(envProviders []EnvProvider, outputPath string) error {
	writer := NewConfigWriter(outputPath)

	// Set first provider's first model as default if available
	if len(envProviders) > 0 && len(envProviders[0].Models) > 0 {
		writer.SetDefaultModel(envProviders[0].Models[0])
	}

	for _, ep := range envProviders {
		writer.AddEnvProvider(ep)
	}

	return writer.Write()
}

// GenerateConfigFromDiscovery generates a config from both env providers and network discovery
func GenerateConfigFromDiscovery(envProviders []EnvProvider, networkInstances []LocalRouterInstance, outputPath string) error {
	writer := NewConfigWriter(outputPath)

	// Set first provider's first model as default if available
	if len(envProviders) > 0 && len(envProviders[0].Models) > 0 {
		writer.SetDefaultModel(envProviders[0].Models[0])
	}

	for _, ep := range envProviders {
		writer.AddEnvProvider(ep)
	}

	for _, instance := range networkInstances {
		writer.AddNetworkInstance(instance)
	}

	return writer.Write()
}
