package discovery

import (
	"fmt"
	"os"
	"strings"
)

// ConfigWriter handles writing discovered configuration to a YAML file
type ConfigWriter struct {
	Path   string
	Config *GeneratedConfig
}

// GeneratedConfig represents the generated config structure
type GeneratedConfig struct {
	Version   int              `yaml:"version"`
	Logging   LoggingConfig    `yaml:"logging"`
	Routing   RoutingConfig    `yaml:"routing"`
	Providers []ConfigProvider `yaml:"providers,omitempty"`
	Local     LocalConfig      `yaml:"local,omitempty"`
}

// ConfigProvider is a provider configuration that includes models
type ConfigProvider struct {
	ID             string        `yaml:"id"`
	Type           string        `yaml:"type"`
	Endpoint       string        `yaml:"endpoint,omitempty"`
	APIKey         string        `yaml:"api_key,string"`
	ChatPath       string        `yaml:"chat_path,omitempty"`
	TimeoutMs      int           `yaml:"timeout_ms,omitempty"`
	RecoveryWindow string        `yaml:"recovery_window"`
	Limits         []LimitConfig `yaml:"limits,omitempty"`
	Models         []ModelConfig `yaml:"models"`
}

// LimitConfig represents rate limits for a provider
type LimitConfig struct {
	Requests    int    `yaml:"requests"`
	Window      string `yaml:"window"`
	IsFreeLimit bool   `yaml:"is_free,omitempty"`
}

// ModelConfig represents a model configuration
type ModelConfig struct {
	ID     string `yaml:"id"`
	IsFree bool   `yaml:"is_free,omitempty"`
}

// LoggingConfig controls log verbosity
type LoggingConfig struct {
	Level string `yaml:"level"`
}

// RoutingConfig holds global routing parameters
type RoutingConfig struct {
	DefaultModel       string `yaml:"default_model"`
	LatencyThresholdMs int    `yaml:"latency_threshold_ms"`
	FallbackEnabled    bool   `yaml:"fallback_enabled"`
}

// LocalConfig contains local node definitions
type LocalConfig struct {
	Nodes []ConfigProvider `yaml:"nodes,omitempty"`
}

// NewConfigWriter creates a new ConfigWriter
func NewConfigWriter(path string) *ConfigWriter {
	return &ConfigWriter{
		Path: path,
		Config: &GeneratedConfig{
			Version: 2,
			Logging: LoggingConfig{Level: "INFO"},
			Routing: RoutingConfig{
				DefaultModel:       "",
				LatencyThresholdMs: 2000,
				FallbackEnabled:    true,
			},
			Providers: make([]ConfigProvider, 0),
		},
	}
}

// SetDefaultModel sets the default model for routing
func (w *ConfigWriter) SetDefaultModel(model string) {
	w.Config.Routing.DefaultModel = model
}

// AddEnvProvider adds an environment-based provider to the config with its models
func (w *ConfigWriter) AddEnvProviderWithModels(pm ProviderModels) {
	p := pm.Provider
	cp := ConfigProvider{
		ID:             p.ID,
		Type:           p.Type,
		Endpoint:       p.Endpoint,
		APIKey:         fmt.Sprintf("${%s}", p.EnvVar),
		RecoveryWindow: p.RecoveryWindow,
		TimeoutMs:      p.TimeoutMs,
	}

	if p.IsFree {
		cp.Limits = []LimitConfig{{Requests: 100, Window: "1m"}}
		for _, m := range pm.Models {
			cp.Models = append(cp.Models, ModelConfig{ID: m, IsFree: true})
		}
	} else {
		for _, m := range pm.Models {
			cp.Models = append(cp.Models, ModelConfig{ID: m})
		}
	}

	w.Config.Providers = append(w.Config.Providers, cp)
}

// AddNetworkInstance adds a discovered network instance as a local node
func (w *ConfigWriter) AddNetworkInstance(instance LocalRouterInstance) {
	cp := ConfigProvider{
		ID:             fmt.Sprintf("localrouter-%s", strings.ReplaceAll(instance.IP, ".", "-")),
		Type:           "openai-compatible",
		Endpoint:       fmt.Sprintf("http://%s:%s/v1", instance.IP, instance.Port),
		APIKey:         "",
		RecoveryWindow: "5m",
		TimeoutMs:      30000,
	}
	for _, m := range instance.Models {
		cp.Models = append(cp.Models, ModelConfig{ID: m})
	}
	w.Config.Providers = append(w.Config.Providers, cp)
}

// Write generates and writes the configuration to a YAML file
func (w *ConfigWriter) Write() error {
	var lines []string

	lines = append(lines, "# Generated by LocalRouter Discovery")
	lines = append(lines, fmt.Sprintf("# Providers discovered: %d", len(w.Config.Providers)))
	lines = append(lines, "")

	lines = append(lines, "version: 2")

	lines = append(lines, "")
	lines = append(lines, "logging:")
	lines = append(lines, fmt.Sprintf("  level: %s", w.Config.Logging.Level))

	lines = append(lines, "")
	lines = append(lines, "routing:")
	if w.Config.Routing.DefaultModel != "" {
		lines = append(lines, fmt.Sprintf("  default_model: %s", w.Config.Routing.DefaultModel))
	}
	lines = append(lines, fmt.Sprintf("  latency_threshold_ms: %d", w.Config.Routing.LatencyThresholdMs))

	if len(w.Config.Providers) > 0 {
		lines = append(lines, "")
		lines = append(lines, "providers:")

		for _, p := range w.Config.Providers {
			lines = append(lines, "")
			lines = append(lines, fmt.Sprintf("  - id: %s", p.ID))
			lines = append(lines, fmt.Sprintf("    type: %s", p.Type))
			if p.Endpoint != "" {
				lines = append(lines, fmt.Sprintf("    endpoint: %s", p.Endpoint))
			}
			if p.APIKey != "" {
				lines = append(lines, fmt.Sprintf("    api_key: %s", p.APIKey))
			}
			if p.ChatPath != "" {
				lines = append(lines, fmt.Sprintf("    chat_path: %s", p.ChatPath))
			}
			lines = append(lines, fmt.Sprintf("    recovery_window: %s", p.RecoveryWindow))
			if p.TimeoutMs > 0 {
				lines = append(lines, fmt.Sprintf("    timeout_ms: %d", p.TimeoutMs))
			}

			if len(p.Limits) > 0 {
				lines = append(lines, "    limits:")
				for _, lim := range p.Limits {
					lines = append(lines, fmt.Sprintf("      requests: %d", lim.Requests))
					lines = append(lines, fmt.Sprintf("      window: %s", lim.Window))
				}
			}

			lines = append(lines, "    models:")
			for _, m := range p.Models {
				lines = append(lines, fmt.Sprintf("      - id: %s", m.ID))
				if m.IsFree {
					lines = append(lines, "        is_free: true")
				}
			}
		}
	}

	content := strings.Join(lines, "\n")
	return os.WriteFile(w.Path, []byte(content), 0644)
}

// GenerateConfigFromEnv generates a config from discovered environment providers
func GenerateConfigFromEnv(providers []ProviderModels, outputPath string) error {
	if len(providers) == 0 {
		return fmt.Errorf("no providers to configure")
	}

	writer := NewConfigWriter(outputPath)

	for _, pm := range providers {
		writer.AddEnvProviderWithModels(pm)
	}

	if len(providers[0].Models) > 0 {
		writer.SetDefaultModel(providers[0].Models[0])
	}

	return writer.Write()
}

// GenerateConfigFromDiscovery generates a config from both env providers and network discovery
func GenerateConfigFromDiscovery(envProviders []ProviderModels, networkInstances []LocalRouterInstance, outputPath string) error {
	if len(envProviders) == 0 && len(networkInstances) == 0 {
		return fmt.Errorf("no providers to configure")
	}

	writer := NewConfigWriter(outputPath)

	for _, pm := range envProviders {
		writer.AddEnvProviderWithModels(pm)
	}

	for _, instance := range networkInstances {
		writer.AddNetworkInstance(instance)
	}

	if len(envProviders) > 0 && len(envProviders[0].Models) > 0 {
		writer.SetDefaultModel(envProviders[0].Models[0])
	} else if len(networkInstances) > 0 && len(networkInstances[0].Models) > 0 {
		writer.SetDefaultModel(networkInstances[0].Models[0])
	}

	return writer.Write()
}
